spring:
  application:
    name: odin-api
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}:${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        connection:
          provider_disables_autocommit: true
    show-sql: false
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 1
      minimum-idle: 0
      auto-commit: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    com.fiap.odin: DEBUG
